// Copy of ../Jenkinsfile
pipeline {
    agent any
    stages {
        stage('Athena') {
            steps {
                sh '''
                set +x
                python3 -m pip install "athena-sast==1.1.1"
                athena scan --local . --modes pipeline --fail-on high --format table
                '''
            }
        }
    }
}
