"""CICD-SEC-7: insecure system configuration — weak crypto and TLS."""

RULES = [
    {
        "id": "ATH020",
        "name": "MD5 usage",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-327",
        "patterns": [r"hashlib\.md5\s*\(", r"(?<![A-Za-z])md5\s*\("],
        "message": "MD5 is not acceptable for security. Use SHA-256 or a password KDF.",
        "tags": ["security", "crypto", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH021",
        "name": "SHA1 usage",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-327",
        "patterns": [r"hashlib\.sha1\s*\("],
        "message": "SHA-1 is deprecated for security. Use SHA-256 or stronger.",
        "tags": ["security", "crypto", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".go", ".java"],
        "mode": "line",
    },
    {
        "id": "ATH022",
        "name": "Insecure random",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-330",
        "patterns": [
            r"random\.(randint|random|choice|randrange)\s*\(",
            r"Math\.random\s*\(",
        ],
        "message": "Non-crypto RNG used. For tokens/keys use secrets / crypto.randomBytes.",
        "tags": ["security", "crypto", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts"],
        "mode": "line",
    },
    {
        "id": "ATH023",
        "name": "SSL verification disabled",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-295",
        "patterns": [
            r"verify\s*=\s*False",
            r"ssl\._create_unverified_context",
            r"rejectUnauthorized\s*:\s*false",
        ],
        "message": "TLS certificate verification is disabled. Keep verify=True / rejectUnauthorized true.",
        "tags": ["security", "tls", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH024",
        "name": "Static IV or salt",
        "severity": "medium",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-329",
        "patterns": [
            r"""(?i)(iv|salt)\s*=\s*b?['"][A-Za-z0-9+/=]{4,}['"]""",
        ],
        "message": "Hardcoded IV or salt. Generate a unique value per encryption.",
        "tags": ["security", "crypto", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".go", ".java"],
        "mode": "line",
    },
    {
        "id": "ATH025",
        "name": "Weak cipher",
        "severity": "medium",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-327",
        "patterns": [r"(?i)\b(DES|RC4|Blowfish|ARC4)\b"],
        "message": "Weak cipher (DES/RC4/Blowfish). Use AES-GCM or ChaCha20-Poly1305.",
        "tags": ["security", "crypto", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH026",
        "name": "Debug enabled in config",
        "severity": "medium",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-489",
        "patterns": [r"(?i)(DEBUG|debug)\s*[:=]\s*(True|true|1)"],
        "message": "Debug mode enabled in a committed config. Disable in production.",
        "tags": ["security", "config", "CICD-SEC-7"],
        "file_types": [".py", ".yml", ".yaml", ".json", ".env", ".ini", ".cfg"],
        "mode": "line",
    },
    {
        "id": "ATH029",
        "name": "Legacy TLS protocol",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-327",
        "patterns": [r"(?i)(TLSv?1\.[01]|SSLv3)"],
        "message": "TLS 1.0/1.1 or SSLv3 is obsolete. Require TLS 1.2+.",
        "tags": ["security", "tls", "CICD-SEC-7"],
        "file_types": [".py", ".js", ".ts", ".yml", ".yaml", ".tf", ".conf"],
        "mode": "line",
    },
]
