"""CICD-SEC-7 / CICD-SEC-2: IaC misconfigurations (Terraform, Kubernetes, Docker)."""

RULES = [
    {
        "id": "ATH027",
        "name": "Kubernetes runAsNonRoot disabled",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"runAsNonRoot:\s*false"],
        "message": "Container may run as root. Set runAsNonRoot: true.",
        "tags": ["security", "k8s", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH028",
        "name": "Docker USER root",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"(?i)^USER\s+root\s*$"],
        "message": "Container image runs as root. Switch to a non-root USER.",
        "tags": ["security", "docker", "CICD-SEC-7"],
        "file_types": [".dockerfile"],
        "filenames": ["Dockerfile", "dockerfile"],
        "mode": "line",
    },
    {
        "id": "ATH030",
        "name": "Public S3 bucket ACL",
        "severity": "critical",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-284",
        "patterns": [r"""acl\s*=\s*["']public-read["']"""],
        "message": "S3 bucket ACL is public-read. Keep buckets private and use IAM.",
        "tags": ["security", "terraform", "s3", "CICD-SEC-7"],
        "file_types": [".tf"],
        "mode": "line",
    },
    {
        "id": "ATH031",
        "name": "SSH/RDP open to the world",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-284",
        "patterns": [r"0\.0\.0\.0/0"],
        "near_patterns": [r"(from_port|to_port)\s*=\s*(22|3389)"],
        "window": 8,
        "message": "Port 22 or 3389 is open to 0.0.0.0/0. Restrict CIDR to trusted networks.",
        "tags": ["security", "terraform", "network", "CICD-SEC-7"],
        "file_types": [".tf"],
        "mode": "window",
    },
    {
        "id": "ATH032",
        "name": "Privileged Kubernetes container",
        "severity": "critical",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"privileged:\s*true"],
        "message": "privileged: true grants host-level access. Remove it.",
        "tags": ["security", "k8s", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH033",
        "name": "Kubernetes hostNetwork enabled",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-668",
        "patterns": [r"hostNetwork:\s*true"],
        "message": "hostNetwork: true shares the host network namespace. Disable it.",
        "tags": ["security", "k8s", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH034",
        "name": "Docker Compose privileged mode",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"privileged:\s*true"],
        "message": "Compose service runs privileged. Drop the flag and use capabilities.",
        "tags": ["security", "docker", "CICD-SEC-7"],
        "filenames": ["docker-compose.yml", "docker-compose.yaml", "compose.yml"],
        "file_types": [".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH035",
        "name": "Unencrypted RDS storage",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-311",
        "patterns": [r"storage_encrypted\s*=\s*false"],
        "message": "RDS storage_encrypted is false. Enable encryption at rest.",
        "tags": ["security", "terraform", "rds", "CICD-SEC-7"],
        "file_types": [".tf"],
        "mode": "line",
    },
    {
        "id": "ATH036",
        "name": "S3 bucket without encryption block",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-311",
        "patterns": [],
        "all_patterns": [r"resource\s+\"aws_s3_bucket\""],
        "missing_patterns": [r"server_side_encryption_configuration"],
        "message": "aws_s3_bucket without server_side_encryption_configuration. Add SSE-S3 or SSE-KMS.",
        "tags": ["security", "terraform", "s3", "CICD-SEC-7"],
        "file_types": [".tf"],
        "mode": "file",
    },
    {
        "id": "ATH037",
        "name": "Kubernetes container missing resource limits",
        "severity": "medium",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-770",
        "patterns": [],
        "all_patterns": [r"containers:"],
        "missing_patterns": [r"limits:"],
        "message": "Container spec has no resource limits. Set cpu/memory limits.",
        "tags": ["security", "k8s", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "k8s_only": True,
        "mode": "file",
    },
    {
        "id": "ATH038",
        "name": "allowPrivilegeEscalation enabled",
        "severity": "high",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"allowPrivilegeEscalation:\s*true"],
        "message": "allowPrivilegeEscalation: true. Set it to false.",
        "tags": ["security", "k8s", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH039",
        "name": "IAM Action and Resource star",
        "severity": "high",
        "owasp_id": "CICD-SEC-2",
        "cwe": "CWE-732",
        "patterns": [r"""Action\s*=\s*["']\*["']"""],
        "near_patterns": [r"""Resource\s*=\s*["']\*["']"""],
        "window": 12,
        "message": "IAM policy grants Action=* and Resource=*. Scope both to least privilege (CICD-SEC-2).",
        "tags": ["security", "iam", "terraform", "CICD-SEC-2"],
        "file_types": [".tf", ".json"],
        "mode": "window",
    },
]
