"""CICD-SEC-4: poisoned pipeline execution and unsafe dynamic execution."""

RULES = [
    {
        "id": "ATH010",
        "name": "SQL injection via string concat",
        "severity": "critical",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-89",
        "patterns": [
            r"""(?i)(execute|executemany|query|raw)\s*\(\s*(f["']|["'].*\+|["'].*%|`.*)""",
            r"""(?i)(execute|query)\s*\(\s*["'].*%s.*["']\s*%""",
            r"""(?i)(cursor\.execute|db\.query)\s*\(\s*f['"]""",
        ],
        "message": "SQL built by string concatenation or f-string. Use parameterized queries.",
        "tags": ["security", "injection", "sqli", "CICD-SEC-4"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH011",
        "name": "OS command injection",
        "severity": "critical",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-78",
        "patterns": [
            r"""(?i)(os\.system|os\.popen|subprocess\.(?:call|run|Popen))\s*\(\s*(f["']|.+\+)""",
            r"""(?i)(child_process\.exec|execSync|spawn)\s*\(\s*[`'"].*\$\{""",
        ],
        "message": "OS command built from dynamic strings. Use argument lists, never a shell string.",
        "tags": ["security", "injection", "command", "CICD-SEC-4"],
        "file_types": [".py", ".js", ".ts", ".go", ".rb", ".sh"],
        "mode": "line",
    },
    {
        "id": "ATH012",
        "name": "Dangerous eval or exec",
        "severity": "critical",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-95",
        "patterns": [
            r"""(?i)(?<![A-Za-z_])(eval|exec)\s*\(\s*[^)]*(input|request|argv|sys\.argv|f["'])""",
            r"""(?i)(?<![A-Za-z_])(eval|exec)\s*\(\s*[f"']""",
            r"""(?i)(?<![A-Za-z_])eval\s*\(""",
        ],
        "message": "eval/exec on dynamic input. Replace with a safe parser or allow-list.",
        "tags": ["security", "injection", "eval", "CICD-SEC-4"],
        "file_types": [".py", ".js", ".ts"],
        "mode": "line",
    },
    {
        "id": "ATH013",
        "name": "Pickle deserialization",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-502",
        "patterns": [r"pickle\.loads?\s*\("],
        "message": "pickle.load/loads can execute attacker payloads. Use json or a signed format.",
        "tags": ["security", "deserialization", "CICD-SEC-4"],
        "file_types": [".py"],
        "mode": "line",
    },
    {
        "id": "ATH014",
        "name": "YAML unsafe load",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-502",
        "patterns": [r"yaml\.load\s*\((?!.*Loader\s*=\s*yaml\.SafeLoader)"],
        "message": "yaml.load without SafeLoader. Use yaml.safe_load().",
        "tags": ["security", "deserialization", "CICD-SEC-4"],
        "file_types": [".py"],
        "mode": "line",
    },
    {
        "id": "ATH015",
        "name": "Template injection markers",
        "severity": "medium",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-94",
        "patterns": [r"""['"].*\{\{.*\}\}.*['"]"""],
        "message": "User-controlled template markers in a string. Sanitize or use a sandboxed template engine.",
        "tags": ["security", "ssti", "CICD-SEC-4"],
        "file_types": [".py", ".js", ".ts", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH016",
        "name": "GitHub Actions expression injection in run",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-94",
        "patterns": [r"run:.*\$\{\{\s*github\.event\."],
        "message": "Untrusted github.event.* interpolated into run:. Pass via env: instead (CICD-SEC-4 PPE).",
        "tags": ["security", "ppe", "github-actions", "CICD-SEC-4"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH017",
        "name": "Jenkins unsanitized params in sh",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-78",
        "patterns": [r"""sh\s+['"]\$\{params\."""],
        "message": "Jenkins sh interpolates params into a shell string. Use env vars and quoting.",
        "tags": ["security", "ppe", "jenkins", "CICD-SEC-4"],
        "filenames": ["Jenkinsfile"],
        "file_types": [".groovy"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH018",
        "name": "PR checkout without persist-credentials false",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-269",
        "patterns": [],
        "all_patterns": [r"pull_request", r"actions/checkout"],
        "missing_patterns": [r"persist-credentials:\s*false"],
        "message": "PR workflow checks out code without persist-credentials: false. Token may leak to untrusted code.",
        "tags": ["security", "ppe", "github-actions", "CICD-SEC-4"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
    {
        "id": "ATH019",
        "name": "GitLab CI commit message interpolated into script",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-94",
        "patterns": [r"\$CI_COMMIT_MESSAGE"],
        "message": "CI_COMMIT_MESSAGE is attacker-controlled. Do not interpolate it into a script.",
        "tags": ["security", "ppe", "gitlab", "CICD-SEC-4"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
]
