"""CICD-SEC-3 / CICD-SEC-9: dependency and artifact integrity."""

RULES = [
    {
        "id": "ATH050",
        "name": "pip install without hash verification",
        "severity": "high",
        "owasp_id": "CICD-SEC-9",
        "cwe": "CWE-494",
        "patterns": [r"pip3? install\b(?!.*--require-hashes)"],
        "message": "pip install without --require-hashes. Verify package integrity (CICD-SEC-9).",
        "tags": ["security", "integrity", "pip", "CICD-SEC-9"],
        "file_types": [".yml", ".yaml", ".sh"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH051",
        "name": "requirements.txt without pinned versions",
        "severity": "high",
        "owasp_id": "CICD-SEC-3",
        "cwe": "CWE-829",
        "patterns": [r"^[A-Za-z0-9][\w\-]*\s*$"],
        "message": "Package listed without ==version. Pin every dependency (CICD-SEC-3).",
        "tags": ["security", "integrity", "pip", "CICD-SEC-3"],
        "file_types": [".txt"],
        "filenames": ["requirements.txt", "requirements-dev.txt"],
        "mode": "line",
    },
    {
        "id": "ATH052",
        "name": "curl | sh remote execution",
        "severity": "high",
        "owasp_id": "CICD-SEC-9",
        "cwe": "CWE-494",
        "patterns": [
            r"curl\b.*\|\s*(ba)?sh",
            r"wget\b.*\|\s*(ba)?sh",
        ],
        "message": "Piping curl/wget into a shell runs unverified remote code. Download, verify checksum, then run.",
        "tags": ["security", "integrity", "CICD-SEC-9"],
        "file_types": [".sh", ".yml", ".yaml", ".py"],
        "mode": "line",
    },
    {
        "id": "ATH053",
        "name": "Docker image without digest pin",
        "severity": "medium",
        "owasp_id": "CICD-SEC-9",
        "cwe": "CWE-829",
        "patterns": [r"(?i)^FROM\s+\S+:\S+(?!.*@sha256:)"],
        "message": "FROM uses a tag without @sha256 digest. Pin the image digest (CICD-SEC-9).",
        "tags": ["security", "docker", "integrity", "CICD-SEC-9"],
        "file_types": [".dockerfile", ".yml", ".yaml"],
        "filenames": ["Dockerfile", "dockerfile"],
        "mode": "line",
    },
    {
        "id": "ATH054",
        "name": "npm install without --ignore-scripts",
        "severity": "medium",
        "owasp_id": "CICD-SEC-3",
        "cwe": "CWE-506",
        "patterns": [r"npm install\b(?!.*--ignore-scripts)"],
        "message": "npm install without --ignore-scripts can run untrusted lifecycle scripts (CICD-SEC-3).",
        "tags": ["security", "npm", "CICD-SEC-3"],
        "file_types": [".yml", ".yaml", ".sh"],
        "pipeline_only": True,
        "mode": "line",
    },
]
