"""CICD-SEC-1,2,5,6,8,10: pipeline config scanning."""

RULES = [
    {
        "id": "ATH040",
        "name": "Secret literal in pipeline env block",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"""^\s*\w+:\s*["'][A-Za-z0-9+/=_\-]{16,}["']"""],
        "near_patterns": [r"^\s*env:"],
        "window": 20,
        "message": "Literal secret in a pipeline env block. Use the CI secrets store, never a hardcoded value.",
        "tags": ["security", "pipeline", "secrets", "CICD-SEC-6"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "window",
    },
    {
        "id": "ATH041",
        "name": "Unpinned third-party GitHub Action",
        "severity": "high",
        "owasp_id": "CICD-SEC-8",
        "cwe": "CWE-829",
        "patterns": [
            r"uses:\s*\S+@(main|master|latest|HEAD|v\d[\w.\-]*)\b"
        ],
        "message": (
            "GitHub Action pinned to a mutable tag (@v1/@main/@latest). "
            "Pin uses: to a full 40-character commit SHA (CICD-SEC-8)."
        ),
        "tags": ["security", "pipeline", "supply-chain", "CICD-SEC-8"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH042",
        "name": "pull_request_target with untrusted checkout",
        "severity": "high",
        "owasp_id": "CICD-SEC-4",
        "cwe": "CWE-94",
        "patterns": [],
        "all_patterns": [r"pull_request_target", r"actions/checkout"],
        "message": "pull_request_target plus actions/checkout can run untrusted PR code with secrets (PPE).",
        "tags": ["security", "pipeline", "ppe", "CICD-SEC-4"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
    {
        "id": "ATH043",
        "name": "Excessive GitHub Actions permissions",
        "severity": "high",
        "owasp_id": "CICD-SEC-5",
        "cwe": "CWE-732",
        "patterns": [r"permissions:\s*write-all"],
        "message": "permissions: write-all (or missing least-privilege permissions). Declare minimal permissions (CICD-SEC-5).",
        "tags": ["security", "pipeline", "pbac", "CICD-SEC-5"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH043B",
        "name": "Missing GitHub Actions permissions block",
        "severity": "high",
        "owasp_id": "CICD-SEC-5",
        "cwe": "CWE-732",
        "patterns": [],
        "all_patterns": [r"(?m)^on:", r"(?m)^jobs:"],
        "missing_patterns": [r"permissions:"],
        "message": "GitHub workflow has no permissions: block. Default GITHUB_TOKEN is overly broad (CICD-SEC-5).",
        "tags": ["security", "pipeline", "pbac", "CICD-SEC-5"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
        "emit_as": "ATH043",
        "emit_name": "Excessive GitHub Actions permissions",
    },
    {
        "id": "ATH044",
        "name": "Auto-merge onto main without review signal",
        "severity": "medium",
        "owasp_id": "CICD-SEC-1",
        "cwe": "CWE-285",
        "patterns": [r"github\.ref\s*==\s*'refs/heads/main'"],
        "missing_patterns": [r"(review|environment:|required_reviewers)"],
        "message": "Deploys to main without a required review/environment gate (CICD-SEC-1).",
        "tags": ["security", "pipeline", "flow-control", "CICD-SEC-1"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
    {
        "id": "ATH045",
        "name": "Docker privileged flag in pipeline",
        "severity": "medium",
        "owasp_id": "CICD-SEC-7",
        "cwe": "CWE-250",
        "patterns": [r"docker\s+run.*--privileged"],
        "message": "Pipeline runs docker --privileged. Drop the flag (CICD-SEC-7).",
        "tags": ["security", "pipeline", "docker", "CICD-SEC-7"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH046",
        "name": "No logging or artifact upload in pipeline",
        "severity": "medium",
        "owasp_id": "CICD-SEC-10",
        "cwe": "CWE-778",
        "patterns": [],
        "all_patterns": [r"(jobs:|pipeline\s*\{|stages:)"],
        "missing_patterns": [
            r"upload-artifact",
            r"publish",
            r"sarif",
            r"codeql",
            r"siem",
            r"archiveArtifacts",
            r"PublishBuildArtifacts",
            r"PublishPipelineArtifact",
        ],
        "message": "Pipeline has no artifact/SARIF/audit publish step (CICD-SEC-10).",
        "tags": ["security", "pipeline", "logging", "CICD-SEC-10"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
    {
        "id": "ATH047",
        "name": "Unpinned dependency install in pipeline",
        "severity": "high",
        "owasp_id": "CICD-SEC-3",
        "cwe": "CWE-829",
        "patterns": [
            r"pip install\s+[A-Za-z0-9_.-]+\s*(?:$|#)",
            r"pip3 install\s+[A-Za-z0-9_.-]+\s*(?:$|#)",
            r"npm install\s+[A-Za-z0-9@/_.-]+\s*(?:$|#)",
        ],
        "message": "Pipeline installs a package without a pinned version (== or lockfile). Pin it (CICD-SEC-3).",
        "tags": ["security", "pipeline", "supply-chain", "CICD-SEC-3"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "line",
    },
    {
        "id": "ATH048",
        "name": "contents: write on pull_request",
        "severity": "high",
        "owasp_id": "CICD-SEC-2",
        "cwe": "CWE-732",
        "patterns": [],
        "all_patterns": [r"pull_request", r"contents:\s*write"],
        "message": "contents: write on a pull_request workflow can let a fork push to the repo (CICD-SEC-2).",
        "tags": ["security", "pipeline", "iam", "CICD-SEC-2"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
    {
        "id": "ATH049",
        "name": "Production deploy without environment protection",
        "severity": "medium",
        "owasp_id": "CICD-SEC-1",
        "cwe": "CWE-285",
        "patterns": [r"(?i)(deploy.*prod|environment:\s*production)"],
        "missing_patterns": [r"environment:"],
        "message": "Production deploy without a GitHub environment protection gate (CICD-SEC-1).",
        "tags": ["security", "pipeline", "flow-control", "CICD-SEC-1"],
        "file_types": [".yml", ".yaml"],
        "pipeline_only": True,
        "mode": "file",
    },
]
