"""CICD-SEC-6: credential hygiene. Secrets must never be hardcoded."""

RULES = [
    {
        "id": "ATH001",
        "name": "Hardcoded password",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"""(?i)password\s*=\s*['"][^'"]{4,}['"]"""],
        "message": "Hardcoded password literal. Load from a secret store or environment variable.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH002",
        "name": "Hardcoded API or secret key",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [
            r"""(?i)(api[_-]?key|secret_key|secret|access_token|auth_token)\s*[:=]\s*['"][^'"]{8,}['"]"""
        ],
        "message": "Hardcoded API/secret key (≥8 character literal). Use a vault or CI secrets store.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH003",
        "name": "AWS Access Key literal",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"AKIA[0-9A-Z]{16}"],
        "message": "AWS access key ID embedded in source. Rotate the key and move it to a secrets manager.",
        "tags": ["security", "secrets", "aws", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml", ".tf", ".json"],
        "mode": "line",
    },
    {
        "id": "ATH004",
        "name": "Private key block",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-321",
        "patterns": [r"-----BEGIN[A-Z ]*PRIVATE KEY-----"],
        "message": "Private key material in the repository. Remove it, rotate, and store in a vault.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml", ".pem", ".key"],
        "mode": "line",
    },
    {
        "id": "ATH005",
        "name": ".env secret assignment",
        "severity": "high",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"(?i)(SECRET|KEY|TOKEN|PASSWORD)\s*=\s*\S+"],
        "message": ".env files with secret values must not be committed. Use secret injection at runtime.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".env"],
        "filenames": [".env"],
        "mode": "line",
    },
    {
        "id": "ATH006",
        "name": "Secret printed to log or console",
        "severity": "high",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-532",
        "patterns": [
            r"(?i)(print|console\.log|logger\.(?:info|debug|warning|error)|logging\.\w+)\s*\(.*?(password|secret|token|api_key|apikey)"
        ],
        "message": "Secret value printed to logs or console. Redact before logging.",
        "tags": ["security", "secrets", "logging", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb"],
        "mode": "line",
    },
    {
        "id": "ATH007",
        "name": "Credentials embedded in URL",
        "severity": "medium",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"https?://[^/\s:]+:[^@\s]+@"],
        "message": "Username/password embedded in a URL. Use a credential helper or header auth instead.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".yml", ".yaml", ".env"],
        "mode": "line",
    },
    {
        "id": "ATH008",
        "name": "Hardcoded JWT",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"],
        "message": "JWT literal in source. Treat as a leaked credential and rotate.",
        "tags": ["security", "secrets", "jwt", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml"],
        "mode": "line",
    },
    {
        "id": "ATH009",
        "name": "Cloud or chat token prefix",
        "severity": "critical",
        "owasp_id": "CICD-SEC-6",
        "cwe": "CWE-798",
        "patterns": [r"\b(ghp_|github_pat_|xoxb-|xoxp-|glpat-|sk-live-|sk-test-)[A-Za-z0-9_-]{8,}"],
        "message": "Provider token prefix detected (GitHub/GitLab/Slack/Stripe). Rotate and store in a vault.",
        "tags": ["security", "secrets", "CICD-SEC-6"],
        "file_types": [".py", ".js", ".ts", ".go", ".java", ".rb", ".sh", ".env", ".yml", ".yaml"],
        "mode": "line",
    },
]
